# Generated by Django 5.0.2 on 2024-02-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_position_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(verbose_name='Год выпуска'),
        ),
    ]
