# Generated by Django 5.0.2 on 2024-02-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.IntegerField(editable=False, verbose_name='Возраст'),
        ),
    ]
